configOverride: |
  [global]
  mon_target_pg_per_osd = 64
  mon_max_pg_per_osd = 256

toolbox:
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
